### ISSUE TITLE
ASK - Can .jsc file be used together with pkg?

### ISSUE THREAD

**Issue by lamualfa** [OsamaAbbas/bytenode#121]
I want to hide the source code from my JS code and bundle it into a binary using [pkg](https://github.com/vercel/pkg). Can i do it with this [bytenode](https://github.com/OsamaAbbas/bytenode)?

The idea is that I will create a file that contains the code to run the `.jsc` file that was created using [bytenode](https://github.com/OsamaAbbas/bytenode) and run it inside of the binary that created using [pkg](https://github.com/vercel/pkg).

```js
const bytenode = require('bytenode');

bytenode.runBytecode(bytecodeBuffer);
```

**Comment by liesauer** [comment]
looks like it is impossible if use default bytenode loader.

```javascript
require('bytenode')

module.exports = require('./index.jsc')
```

```
pkg/prelude/bootstrap.js:1872
      throw error;
      ^

RangeError: Invalid string length
    at String.repeat (<anonymous>)
    at Object.Module._extensions.<computed> [as .jsc] (C:\snapshot\xxxxx\node_modules\bytenode\lib\index.js:258:32)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\snapshot\xxxxx\obfuscated\index.loader.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._compile (pkg/prelude/bootstrap.js:1933:32)
```

i tried using `runBytecode` to instead `require`, not working either.

```javascript
const { readFileSync } = require('fs');

require('bytenode')

// module.exports = require('./index.jsc')

bytenode.runBytecode(readFileSync(__dirname + '/index.jsc'));
```


```
C:\snapshot\xxxxx\node_modules\bytenode\lib\index.js:158
    throw new Error('Invalid or incompatible cached data (cachedDataRejected)');
    ^

Error: Invalid or incompatible cached data (cachedDataRejected)
    at Object.runBytecode (C:\snapshot\xxxxx\node_modules\bytenode\lib\index.js:158:11)
    at Object.<anonymous> (C:\snapshot\xxxxx\obfuscated\index.loader.js:7:10)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._compile (pkg/prelude/bootstrap.js:1933:32)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1979:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by OsamaAbbas** [comment]
There ia no point in using bytenode with pkg. Pkg, if I remember correctly, bundles node binary when buildiglng your project. So, it may not be the same binary used in compiling and generating you `.jsc` files. Hence the error thrown. Also, pkg itself has a very similar feature which compile your code into bytecode as well. I don't fully remember or know if they get rid of the plain source code or not, but I think they do.
