### ISSUE TITLE
 Cannot read property 'sync' of undefined

### ISSUE THREAD

**Issue by lstgenesis** [OsamaAbbas/bytenode#21]
genesis@lst-genesis:~/Documents/seqproj3$ bytenode index.jsc
evalmachine.<anonymous>:1
"​​​​​​​​​​�

TypeError: Cannot read property 'sync' of undefined
    at Object.<anonymous> (evalmachine.<anonymous>:1:269)
    at Object.Module._extensions.(anonymous function) [as .jsc] (/home/genesis/.npm-global/lib/node_modules/bytenode/index.js:216:26)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

**Comment by lstgenesis** [comment]
I experienced this problem when I try to bytenode sequelize models. Then I try to add --no-module, then it works.
